import type {
  Release,
  PromotionalTask,
  AiRecommendation,
  CalendarEvent,
  AnalyticsData,
  ArtistProfile,
} from "./types";

export const artistProfile: ArtistProfile = {
  id: "artist-1",
  name: "Nova Kaine",
  genre: "Alternative R&B",
  monthlyListeners: 48320,
  followers: 12450,
  totalStreams: 2_340_000,
  releaseCount: 7,
  topMarkets: ["United States", "United Kingdom", "Canada", "Australia"],
  plan: "pro",
};

export const releases: Release[] = [
  {
    id: "rel-1",
    title: "Midnight Frequencies",
    artist: "Nova Kaine",
    stage: "launch",
    releaseDate: "2026-07-04",
    genre: "Alternative R&B",
    bpm: 92,
    key: "F# Minor",
    description:
      "A moody, late-night anthem blending atmospheric synths with raw vocals. Inspired by city lights and sleepless thoughts.",
    platforms: ["spotify", "apple-music", "youtube", "tiktok", "instagram"],
    streams: 0,
    saves: 0,
    playlistPlacements: 0,
    pressContacts: 12,
    aiScore: 87,
    createdAt: "2026-06-01",
  },
  {
    id: "rel-2",
    title: "Gravity Pull",
    artist: "Nova Kaine",
    stage: "post-release",
    releaseDate: "2026-05-10",
    genre: "Alternative R&B",
    bpm: 105,
    key: "D Minor",
    description:
      "An energetic track exploring emotional turbulence and the pull of relationships.",
    platforms: ["spotify", "apple-music", "youtube", "soundcloud"],
    streams: 124_000,
    saves: 8_900,
    playlistPlacements: 14,
    pressContacts: 8,
    aiScore: 72,
    createdAt: "2026-04-01",
  },
  {
    id: "rel-3",
    title: "Neon Ghost",
    artist: "Nova Kaine",
    stage: "production",
    releaseDate: "2026-08-22",
    genre: "Alternative R&B",
    bpm: 88,
    key: "A Minor",
    description:
      "Upcoming single featuring trap-influenced beats and introspective lyricism.",
    platforms: ["spotify", "apple-music"],
    streams: 0,
    saves: 0,
    playlistPlacements: 0,
    pressContacts: 0,
    aiScore: 91,
    createdAt: "2026-06-15",
  },
];

export const promotionalTasks: PromotionalTask[] = [
  {
    id: "task-1",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Submit to Spotify Editorial Playlists",
    description:
      "Submit 'Midnight Frequencies' to Spotify for Artists editorial consideration at least 7 days before release.",
    platform: "spotify",
    dueDate: "2026-06-27",
    status: "completed",
    priority: "critical",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult:
      "Successfully submitted to 3 editorial playlists: Late Night Vibes, R&B Chill, New Music Friday.",
    category: "playlist",
  },
  {
    id: "task-2",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Create 3 TikTok Teaser Clips",
    description:
      "Extract the catchiest 15-second hook from the track and create 3 unique teaser videos with different visual concepts.",
    platform: "tiktok",
    dueDate: "2026-06-30",
    status: "in-progress",
    priority: "high",
    isAiGenerated: true,
    isAiExecuted: false,
    category: "content",
  },
  {
    id: "task-3",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Press Outreach — Music Blogs",
    description:
      "Send personalized press kits to 12 identified music blogs and online publications.",
    dueDate: "2026-06-28",
    status: "in-progress",
    priority: "high",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult:
      "Personalized emails drafted and sent to Pigeons & Planes, The FADER, Ones To Watch, and 9 others.",
    category: "press",
  },
  {
    id: "task-4",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Instagram Countdown Campaign",
    description:
      "Schedule 7-day countdown posts on Instagram with engaging visuals and interactive stories.",
    platform: "instagram",
    dueDate: "2026-06-27",
    status: "completed",
    priority: "medium",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult:
      "7 posts scheduled across feed and stories. Countdown stickers and question boxes added.",
    category: "social",
  },
  {
    id: "task-5",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Apple Music Pre-Save Campaign",
    description:
      "Set up and promote a pre-save link to build early momentum on Apple Music.",
    platform: "apple-music",
    dueDate: "2026-06-25",
    status: "completed",
    priority: "high",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult: "Pre-save link created and shared. 432 pre-saves captured.",
    category: "distribution",
  },
  {
    id: "task-6",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "YouTube Official Visualizer Upload",
    description:
      "Upload and optimize the official visualizer video on YouTube with SEO-optimized description and tags.",
    platform: "youtube",
    dueDate: "2026-07-04",
    status: "pending",
    priority: "high",
    isAiGenerated: true,
    isAiExecuted: false,
    category: "content",
  },
  {
    id: "task-7",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Release Day Advertising Campaign",
    description:
      "Launch targeted Spotify and Instagram ad campaigns on release day targeting fans of similar artists.",
    dueDate: "2026-07-04",
    status: "pending",
    priority: "critical",
    isAiGenerated: true,
    isAiExecuted: false,
    category: "advertising",
  },
  {
    id: "task-8",
    releaseId: "rel-2",
    releaseTitle: "Gravity Pull",
    title: "Post-Release Playlist Pitching",
    description:
      "Pitch 'Gravity Pull' to independent playlist curators now that it has 7 days of streaming data.",
    platform: "spotify",
    dueDate: "2026-05-20",
    status: "completed",
    priority: "high",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult:
      "Pitched to 34 curators. 14 placements secured, adding 8,200 additional streams.",
    category: "playlist",
  },
  {
    id: "task-9",
    releaseId: "rel-2",
    releaseTitle: "Gravity Pull",
    title: "Monthly Listener Growth Campaign",
    description:
      "Run a 30-day social media content plan to sustain and grow monthly listener count.",
    dueDate: "2026-06-10",
    status: "completed",
    priority: "medium",
    isAiGenerated: true,
    isAiExecuted: true,
    executionResult:
      "Monthly listeners grew from 38,400 to 48,320 (+25.8%) over the campaign period.",
    category: "social",
  },
  {
    id: "task-10",
    releaseId: "rel-3",
    releaseTitle: "Neon Ghost",
    title: "Define Release Strategy",
    description:
      "Review AI-generated release strategy for Neon Ghost and approve key decisions.",
    dueDate: "2026-07-01",
    status: "pending",
    priority: "medium",
    isAiGenerated: true,
    isAiExecuted: false,
    category: "distribution",
  },
];

export const aiRecommendations: AiRecommendation[] = [
  {
    id: "rec-1",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    type: "timing",
    title: "Optimal Release Window Confirmed",
    summary:
      "Friday July 4th aligns with New Music Friday cycles and benefits from lower competition due to the holiday weekend.",
    details:
      "Analysis of 2,400 similar releases shows R&B tracks released on holiday weekends receive 18% more first-week streams on average. The absence of major label drops this week creates editorial whitespace. Spotify editorial submission window closes June 27—already actioned.",
    confidence: 89,
    impact: "high",
    effort: "low",
    createdAt: "2026-06-10",
    isActioned: true,
  },
  {
    id: "rec-2",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    type: "platform",
    title: "Prioritize TikTok Over Instagram for Launch Week",
    summary:
      "Your audience 18–24 demographic is 3x more likely to discover new music via TikTok. Allocate 60% of content effort there.",
    details:
      "Based on 'Gravity Pull' analytics, TikTok drove 34% of your streams despite 20% of your posting effort. The hook at 0:42 of Midnight Frequencies is algorithmically optimized for short-form video (bouncy bassline, lyric hook). Recommended: post 2 TikTok videos before midnight July 3rd to capture early algorithmic momentum.",
    confidence: 82,
    impact: "high",
    effort: "medium",
    createdAt: "2026-06-15",
    isActioned: false,
  },
  {
    id: "rec-3",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    type: "audience",
    title: "Target 'Drive-Time' Listeners for Playlist Placement",
    summary:
      "Track tempo and mood profile matches late-night and commute playlists—the highest-conversion playlist category.",
    details:
      "Midnight Frequencies scores 8.7/10 on the 'late-night' audio profile index (valence 0.32, energy 0.61, tempo 92 BPM). This matches the editorial profile of 'Late Night Vibes' (2.1M followers), 'Night Drive' (1.4M), and 'Chill R&B' (890K). Editorial submission already submitted. Recommend also pitching 18 independent curators of these playlists.",
    confidence: 91,
    impact: "high",
    effort: "low",
    createdAt: "2026-06-18",
    isActioned: true,
  },
  {
    id: "rec-4",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    type: "content",
    title: "Create a 'Making Of' Video Series",
    summary:
      "Behind-the-scenes content drives 2.4x more profile visits and 31% higher save rates than standard promotional posts.",
    details:
      "Artists in your genre who release 3+ behind-the-scenes pieces in the 2 weeks before a launch see significantly higher engagement. Suggested series: (1) Studio session snippet, (2) Lyrics/inspiration story, (3) Day-before release vlog. Each piece should be 60–90 seconds for optimal Instagram Reel and TikTok performance.",
    confidence: 76,
    impact: "medium",
    effort: "medium",
    createdAt: "2026-06-20",
    isActioned: false,
  },
  {
    id: "rec-5",
    releaseId: "rel-2",
    releaseTitle: "Gravity Pull",
    type: "strategy",
    title: "Boost Gravity Pull to Sustain Catalogue Streams",
    summary:
      "Gravity Pull is declining 12% week-over-week. A targeted campaign can stabilize it and maintain catalogue value.",
    details:
      "Monthly listener retention analysis shows tracks in your genre typically stabilize after week 8 if supported by playlist adds. Gravity Pull is at week 7 with 14 placements. Recommend pitching 15 additional curators in the 'energy workout' and 'new R&B' categories, where your track also scores highly (energy 0.78).",
    confidence: 68,
    impact: "medium",
    effort: "medium",
    createdAt: "2026-06-22",
    isActioned: false,
  },
  {
    id: "rec-6",
    releaseId: "rel-3",
    releaseTitle: "Neon Ghost",
    type: "strategy",
    title: "Start Pre-Release Campaign 8 Weeks Before Launch",
    summary:
      "Neon Ghost has the highest AI score (91) of any upcoming release. Begin building anticipation now.",
    details:
      "Based on your audience growth trajectory, Neon Ghost could peak at 180K–220K first-month streams with proper runway. Recommend starting a teaser campaign July 1st (8 weeks out), releasing a snippet/instrumental preview July 22nd, and beginning playlist pitching by August 1st. This timeline mirrors your most successful comparable release pattern.",
    confidence: 85,
    impact: "high",
    effort: "high",
    createdAt: "2026-06-25",
    isActioned: false,
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "ev-1",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Spotify Editorial Submission",
    date: "2026-06-20",
    type: "pitch",
    platform: "spotify",
    isAiScheduled: true,
    description: "Submit for editorial playlist consideration",
  },
  {
    id: "ev-2",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Instagram Countdown Start",
    date: "2026-06-27",
    type: "campaign-start",
    platform: "instagram",
    isAiScheduled: true,
    description: "7-day countdown campaign begins",
  },
  {
    id: "ev-3",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "TikTok Teaser #1",
    date: "2026-06-28",
    type: "content",
    platform: "tiktok",
    isAiScheduled: true,
    description: "First teaser clip — atmospheric visuals",
  },
  {
    id: "ev-4",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Press Kit Send-Out",
    date: "2026-06-28",
    type: "promo",
    isAiScheduled: true,
    description: "Personalized press emails to 12 blogs",
  },
  {
    id: "ev-5",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "TikTok Teaser #2",
    date: "2026-07-01",
    type: "content",
    platform: "tiktok",
    isAiScheduled: true,
    description: "Second teaser — hook-focused lyric video",
  },
  {
    id: "ev-6",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "RELEASE DAY",
    date: "2026-07-04",
    type: "release",
    isAiScheduled: false,
    description: "Midnight Frequencies drops on all platforms",
  },
  {
    id: "ev-7",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "Release Day Ad Campaign Launch",
    date: "2026-07-04",
    type: "campaign-start",
    isAiScheduled: true,
    description: "Spotify + Instagram targeted ad campaigns go live",
  },
  {
    id: "ev-8",
    releaseId: "rel-1",
    releaseTitle: "Midnight Frequencies",
    title: "First-Week Review & Curator Pitching",
    date: "2026-07-11",
    type: "review",
    isAiScheduled: true,
    description: "AI analyzes first-week data and pitches independent curators",
  },
  {
    id: "ev-9",
    releaseId: "rel-2",
    releaseTitle: "Gravity Pull",
    title: "Catalogue Boost Campaign",
    date: "2026-06-28",
    type: "campaign-start",
    isAiScheduled: true,
    description: "Gravity Pull stabilization campaign starts",
  },
  {
    id: "ev-10",
    releaseId: "rel-3",
    releaseTitle: "Neon Ghost",
    title: "Neon Ghost Pre-Campaign Start",
    date: "2026-07-01",
    type: "promo",
    isAiScheduled: true,
    description: "Begin teaser and audience priming campaign",
  },
  {
    id: "ev-11",
    releaseId: "rel-3",
    releaseTitle: "Neon Ghost",
    title: "Neon Ghost RELEASE DAY",
    date: "2026-08-22",
    type: "release",
    isAiScheduled: false,
    description: "Neon Ghost drops on all platforms",
  },
];

export const analyticsData: AnalyticsData[] = [
  {
    releaseId: "rel-2",
    releaseTitle: "Gravity Pull",
    streams: [
      { date: "May 10", streams: 4200, saves: 380, skips: 820 },
      { date: "May 11", streams: 6800, saves: 590, skips: 1100 },
      { date: "May 12", streams: 8100, saves: 710, skips: 980 },
      { date: "May 13", streams: 7200, saves: 640, skips: 1040 },
      { date: "May 14", streams: 9400, saves: 820, skips: 760 },
      { date: "May 15", streams: 7900, saves: 680, skips: 890 },
      { date: "May 16", streams: 6300, saves: 510, skips: 920 },
      { date: "May 17", streams: 5800, saves: 470, skips: 960 },
      { date: "May 24", streams: 4900, saves: 390, skips: 1010 },
      { date: "May 31", streams: 3800, saves: 280, skips: 1100 },
      { date: "Jun 7", streams: 3200, saves: 210, skips: 1200 },
      { date: "Jun 14", streams: 2700, saves: 180, skips: 1300 },
      { date: "Jun 21", streams: 2400, saves: 155, skips: 1380 },
      { date: "Jun 28", streams: 2100, saves: 130, skips: 1420 },
    ],
    demographics: [
      { age: "13–17", percentage: 8 },
      { age: "18–24", percentage: 34 },
      { age: "25–34", percentage: 31 },
      { age: "35–44", percentage: 18 },
      { age: "45+", percentage: 9 },
    ],
    platforms: [
      { platform: "Spotify", streams: 74000, saves: 5200, playlistAdds: 9400 },
      {
        platform: "Apple Music",
        streams: 28000,
        saves: 2100,
        playlistAdds: 3200,
      },
      { platform: "YouTube", streams: 14000, saves: 800, playlistAdds: 200 },
      {
        platform: "SoundCloud",
        streams: 8000,
        saves: 800,
        playlistAdds: 1100,
      },
    ],
    growth: [
      { week: "May W2", followers: 10200, monthlyListeners: 38400 },
      { week: "May W3", followers: 10800, monthlyListeners: 41200 },
      { week: "May W4", followers: 11400, monthlyListeners: 44800 },
      { week: "Jun W1", followers: 11900, monthlyListeners: 46200 },
      { week: "Jun W2", followers: 12100, monthlyListeners: 47100 },
      { week: "Jun W3", followers: 12300, monthlyListeners: 47800 },
      { week: "Jun W4", followers: 12450, monthlyListeners: 48320 },
    ],
  },
];
